name: Deploy

# Trigger the workflow on push and 
# pull request events on the production branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test echo aja
        run: echo "Halo aku bekerja teman"
